export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace" | "approval";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Optional answer choices for a pending ask_user question. */
  buttons?: string[][];
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  preview: string;
  activeTarget?: string | null;
  metadata?: {
    continuity?: {
      canonical_owner_id?: string;
      channel_kind?: string;
      external_identity?: string;
      trust_level?: string;
      last_confirmed_at?: string | null;
    };
    approval_summary?: {
      status?: string;
      channel?: string;
      tool_name?: string;
      tool_call_id?: string;
      message_id?: string | null;
      prompt_preview?: string;
    };
    calendar_pending_interaction?: {
      id?: string;
      kind?: string;
      status?: string;
      question?: string;
      buttons?: string[][];
      request?: Record<string, unknown>;
      conflicts?: Array<Record<string, unknown>>;
      expected_field?: string | null;
      created_at?: string | null;
      updated_at?: string | null;
    };
    calendar_create_approval?: {
      title?: string;
      start_at?: string;
      end_at?: string;
      description?: string | null;
      location?: string | null;
    };
    proactive_summary?: {
      status?: string;
      category?: string;
      title?: string;
      summary?: string;
      target_channel?: string;
      suppressed_reason?: string | null;
      updated_at?: string | null;
    };
    pending_user_turn?: boolean;
    runtime_checkpoint?: {
      phase?: string;
      iteration?: number;
      model?: string;
    };
    task_summary?: {
      task_id?: string;
      canonical_owner_id?: string;
      title?: string;
      status?: string;
      origin_channel?: string;
      origin_session_key?: string;
      updated_at?: string | null;
      next_step_hint?: string;
    };
    owner_profile?: {
      canonical_owner_id?: string;
      preferred_language?: string;
      timezone?: string;
      response_tone?: string;
      response_length?: string;
    };
    memory_boundary?: {
      owner_profile?: string;
      project_memory?: string;
      session_state?: string;
      raw_history?: string;
    };
    memory_correction?: {
      actions?: Array<{
        code?: string;
        phrase?: string;
        target?: string;
        store?: string;
      }>;
    };
    action_result?: {
      action_id?: string;
      domain?: string;
      action?: string;
      status?: string;
      title?: string;
      summary?: string;
      next_step?: string | null;
      visibility?: {
        badge?: string | null;
        inline_status?: string | null;
        linked_summary?: string | null;
      };
      error?: {
        code?: string;
        message?: string;
      } | null;
      details?: {
        draft_id?: string | null;
        message_id?: string | null;
        event_id?: string | null;
        preview?: {
          subject?: string;
          body_preview?: string;
          to_recipients?: string[];
          cc_recipients?: string[];
          bcc_recipients?: string[];
          thread_id?: string | null;
          title?: string;
          start_at?: string;
          end_at?: string;
          location?: string | null;
          description?: string | null;
        };
        mailbox_label?: string | null;
        total_candidates?: number | null;
        summary_text?: string | null;
        window_label?: string | null;
        requested_start_at?: string;
        requested_end_at?: string;
        available?: boolean;
        checked_window_label?: string | null;
        reason?: string | null;
        conflicting_events?: Array<{
          event_id?: string | null;
          title?: string;
          start_at?: string;
          end_at?: string;
          all_day?: boolean;
          location?: string | null;
        }>;
        threads?: Array<{
          thread_id?: string;
          subject?: string;
          sender_summary?: string;
          last_update_at?: string;
          unread?: boolean;
          importance_hint?: string | null;
          snippet?: string | null;
          summary?: string | null;
          urgency?: string | null;
          recommended_next_action?: string | null;
        }>;
      };
    };
  };
}

export interface SessionMessagesResponse {
  key: string;
  created_at: string | null;
  updated_at: string | null;
  metadata?: {
    continuity?: {
      canonical_owner_id?: string;
      channel_kind?: string;
      external_identity?: string;
      trust_level?: string;
      last_confirmed_at?: string | null;
    };
    approval_summary?: {
      status?: string;
      channel?: string;
      tool_name?: string;
      tool_call_id?: string;
      message_id?: string | null;
      prompt_preview?: string;
    };
    calendar_pending_interaction?: {
      id?: string;
      kind?: string;
      status?: string;
      question?: string;
      buttons?: string[][];
      request?: Record<string, unknown>;
      conflicts?: Array<Record<string, unknown>>;
      expected_field?: string | null;
      created_at?: string | null;
      updated_at?: string | null;
    };
    proactive_summary?: {
      status?: string;
      category?: string;
      title?: string;
      summary?: string;
      target_channel?: string;
      suppressed_reason?: string | null;
      updated_at?: string | null;
    };
    pending_user_turn?: boolean;
    runtime_checkpoint?: {
      phase?: string;
      iteration?: number;
      model?: string;
    };
    task_summary?: {
      task_id?: string;
      canonical_owner_id?: string;
      title?: string;
      status?: string;
      origin_channel?: string;
      origin_session_key?: string;
      updated_at?: string | null;
      next_step_hint?: string;
    };
    owner_profile?: {
      canonical_owner_id?: string;
      preferred_language?: string;
      timezone?: string;
      response_tone?: string;
      response_length?: string;
    };
    memory_boundary?: {
      owner_profile?: string;
      project_memory?: string;
      session_state?: string;
      raw_history?: string;
    };
    memory_correction?: {
      actions?: Array<{
        code?: string;
        phrase?: string;
        target?: string;
        store?: string;
      }>;
    };
    action_result?: {
      action_id?: string;
      domain?: string;
      action?: string;
      status?: string;
      title?: string;
      summary?: string;
      next_step?: string | null;
      visibility?: {
        badge?: string | null;
        inline_status?: string | null;
        linked_summary?: string | null;
      };
      error?: {
        code?: string;
        message?: string;
      } | null;
      details?: {
        draft_id?: string | null;
        message_id?: string | null;
        event_id?: string | null;
        preview?: {
          subject?: string;
          body_preview?: string;
          to_recipients?: string[];
          cc_recipients?: string[];
          bcc_recipients?: string[];
          thread_id?: string | null;
          title?: string;
          start_at?: string;
          end_at?: string;
          location?: string | null;
          description?: string | null;
        };
        mailbox_label?: string | null;
        total_candidates?: number | null;
        summary_text?: string | null;
        window_label?: string | null;
        requested_start_at?: string;
        requested_end_at?: string;
        available?: boolean;
        checked_window_label?: string | null;
        reason?: string | null;
        threads?: Array<{
          thread_id?: string;
          subject?: string;
          sender_summary?: string;
          last_update_at?: string;
          unread?: boolean;
          importance_hint?: string | null;
          snippet?: string | null;
          summary?: string | null;
          urgency?: string | null;
          recommended_next_action?: string | null;
        }>;
      };
    };
  };
  messages: Array<{
    role: string;
    content: string;
    timestamp?: string;
    tool_calls?: unknown;
    tool_call_id?: string;
    name?: string;
    buttons?: string[][];
    media_urls?: {
      url: string;
      name?: string;
    }[];
  }>;
}

export interface ModelTargetOption {
  name: string;
  kind: string;
  provider?: string | null;
  model?: string | null;
  description?: string;
  display_name?: string | null;
  group?: string | null;
  smart_router_mode?: "auto" | "local" | "mini" | "full" | null;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
  active_target?: string | null;
  model_targets?: ModelTargetOption[];
}

export interface SessionModelTargetResponse {
  key: string;
  active_target: string;
  target?: ModelTargetOption | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    configured_model?: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
    model_locked?: boolean;
    provider_locked?: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
  }>;
  runtime: {
    config_path: string;
  };
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      response_model?: string;
      active_target?: string;
      media_urls?: Array<{ url: string; name?: string }>;
      buttons?: string[][];
      /** Original prompt before the websocket text fallback appends buttons. */
      button_prompt?: string;
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "tool_approval" | "remote_user";
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
      response_model?: string;
      active_target?: string;
    }
  | { event: "error"; chat_id?: string; detail?: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "session_message";
      session_key: string;
      content: string;
      media?: OutboundMedia[];
    }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
    };
